### ISSUE TITLE
Output Timer

### ISSUE THREAD

**Issue by SpeedyFolf** [lotsofs/LiveSplit.OutputToFile#2]
It'd be nice to have access to the timer (with seconds). People like Joshimuz could use it instead of an external app for marathons for example.

gabrielthomasjacobs commented on Jan 13
This project might be a better fit when trying to get the current time data. https://github.com/LiveSplit/LiveSplit.Server

**Comment by lotsofs** [comment]
Handled in [6e67dc7](https://github.com/lotsofs/LiveSplit.OutputToFile/commit/6e67dc778152f126a926e50b1fcb7415b0bb45be)
